University/Controllers/CourseController.cs
using Services.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace University.Controllers
{
    public class CourseController : Controller
    {
        private readonly IAcessToCourses _acessToCourses;
        public CourseController(IAcessToCourses acessToCourses)
        {
            _acessToCourses = acessToCourses;
        }
        public IActionResult Index()
        {
            var courses = _acessToCourses.GetAll();
            return View(courses);

        }
    }
}

University/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace University.Controllers
{  
    public class GroupController : Controller
    {
        const string SAVE_VALUE = "save";
        const string DELETE_VALUE = "delete";
        const string SUCCESS_RENAMED_MESSAGE = "Group successfully remaned";
        const string SUCCESS_DELETED_MESSAGE = "Group successfully deleted";
        const string UNSUCCESS_DELETED_MESSAGE = "Group cannot be deleted cause it is not empty";

        private readonly IAcessToGroups _acessToGroups;
        private readonly IAcessToCourses _acessToCourses;
        public GroupController(IAcessToGroups acessToGroups, IAcessToCourses acessToCourses)
        {
            _acessToGroups = acessToGroups;
            _acessToCourses = acessToCourses;
        }
        [HttpGet]
        public IActionResult ShowGroups(int id, string message)
        {
            var groups = _acessToGroups.GetByCourseId(id);
            var course = _acessToCourses.GetById(id);
            ViewBag.CourseName = course.Name;
            if (message != null)
            {
                ViewBag.Message = message;
            }
            else
            {
                ViewBag.Message = "";
            }
            return View(groups);
        }
        [HttpGet]
        public IActionResult EditGroup(int id)
        {
            var group = _acessToGroups.GetById(id);
            ViewBag.GroupName = group.Name;
            ViewBag.GroupId = id;
            return View();
        }

        [HttpGet]
        public IActionResult AddGroup(int id)
        {
            ViewBag.CourseId = id;
            var course = _acessToCourses.GetById(id);
            ViewBag.CourseName = course.Name;
            return View();
        }

        [HttpPost]
        public ActionResult ChangeGroupName(int groupId, string newGroupName, string action)
        {
            var group = _acessToGroups.GetById(groupId); 
            int courseId = group.Course_id;

            if (action == SAVE_VALUE)
            {
                group.Name = newGroupName;
                _acessToGroups.Update(group);
            }
            else if (action == DELETE_VALUE)
            {
                return RedirectToAction("DeleteGroup", "Group", new { @id = groupId});
            }
            return RedirectToAction("ShowGroups", "Group", new { @id = courseId , @message = SUCCESS_RENAMED_MESSAGE });

        }
        public IActionResult DeleteGroup(int id)
        {
            var group = _acessToGroups.GetById(id); 
            bool isGroupEmpty = _acessToGroups.IsGroupEmpty(id);
            int courseId = group.Course_id;
            if (isGroupEmpty)
            {
                _acessToGroups.Delete(group);
            }
            else
            {
                return RedirectToAction("ShowGroups", "Group", new { @id = courseId, @message = UNSUCCESS_DELETED_MESSAGE });
            }
            return RedirectToAction("ShowGroups", "Group", new { @id = courseId, @message = SUCCESS_DELETED_MESSAGE });
        }


        [HttpPost]
        public ActionResult AddNewGroup(int courseId, string newGroupName, string action)
        {
            if (action == SAVE_VALUE)
            {
                Group group = new Group();
                group.Course_id = courseId;
                group.Name = newGroupName;
                _acessToGroups.Add(group);
             }
           
            return RedirectToAction("ShowGroups", "Group", new { @id = courseId });

        }
    }
    }

University/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Services.Interfaces;



namespace University.Controllers
{
    
    public class StudentController : Controller
    {
        const string SAVE_VALUE = "save";
        const string DELETE_VALUE = "delete";

        private readonly IAcessToStudents _acessToStudents;
        private readonly IAcessToGroups _acessToGroups;
        public StudentController(IAcessToStudents acessToStudents, IAcessToGroups acessToGroups)
        {
            _acessToStudents = acessToStudents;
            _acessToGroups = acessToGroups;
        }
        [HttpGet]
        public IActionResult EditStudent(int id)
        {
            var student = _acessToStudents.GetById(id);
            ViewBag.FirstName = student.FirstName;
            ViewBag.LastName = student.LastName;
            ViewBag.StudentId = id;
            return View();
        }
        [HttpPost]
        public ActionResult ChangeStudentName(int studentid, string newFirstName, string newLastName, string action)
        {
            var student = _acessToStudents.GetById(studentid);
            var groupId = student.GroupId;
            if (action == SAVE_VALUE)
            {
                student.FirstName = newFirstName;
                student.LastName = newLastName;
                _acessToStudents.Update(student);
            }
            else if (action == DELETE_VALUE)
            {
                _acessToStudents.Delete(student);
            }
            return RedirectToAction("ShowStudents", "Student", new { @id = groupId });
        }
        [HttpPost]
        public ActionResult AddNewStudent(int groupid, string newFirstName, string newLastName, string action)
        {
            if (action == SAVE_VALUE)
            {
                Student student = new Student();
                student.FirstName = newFirstName;
                student.LastName = newLastName;
                student.GroupId = groupid;
                _acessToStudents.Add(student);
            }
            return RedirectToAction("ShowStudents", "Student", new { @id = groupid });
        }
        public IActionResult AddStudent(int id)
        {
            ViewBag.GroupId = id;
            return View();
        }
        public IActionResult ShowStudents(int id)
        {
            ViewBag.groupId = id;
            var students = _acessToStudents.GetAllByGroupId(id);
            var group = _acessToGroups.GetById(id);   
            ViewBag.courseId = group.Course_id;
            ViewBag.GroupName = group.Name;
            return View(students);
        }
    }
}

University/Views/Course/Index.cshtml
@model IEnumerable<Models.Course>

<!DOCTYPE html>

<html>
<head>
    <title>State University</title>
</head>
<body>
    <h3>Courses</h3>
    <table>
        <tr>
            <td>Course</td>
            <td></td>
        </tr>
        @foreach (var courses in Model)
        {
    <tr>
        <td>@courses.Name</td>
        <td><a href="~/Group/ShowGroups/@courses.CoursesId">Select</a></td>
        <td> | </td>
        <td><a href="~/Group/AddGroup/@courses.CoursesId">Add group</a></td>
    </tr>
        }
    </table>
</body>
</html>

University/Views/Group/AddGroup.cshtml
@using (Html.BeginForm("AddNewGroup", "Group", FormMethod.Post))
{
    <p>Add new group to course @ViewBag.CourseName: </p>
    <br />

    <input type="hidden" value="@ViewBag.CourseId" name="courseid" />
    <input type="text" value="@ViewBag.GroupName" name="newgroupname" />
    <br />
    <button name="action" value="save">Save</button>
    <button name="action" value="cancel">Cancel</button>
}

University/Views/Group/EditGroup.cshtml
@using (Html.BeginForm("ChangeGroupName", "Group", FormMethod.Post))
{
    <p>Enter new name of @ViewBag.GroupName: </p>
    <br />

    <input type="hidden" value="@ViewBag.GroupId" name="groupid" />
    <input type="text" value="@ViewBag.GroupName" name="newgroupname" />
    <br />
    <button name="action" value="save">Save</button>
    <button name="action" value="delete">Delete</button>
    <button name="action" value="cancel">Cancel</button>
}

University/Views/Group/ShowGroups.cshtml
@model IEnumerable<Models.Group>
<!DOCTYPE html>

<html>
<head>
    <title>State University</title>
</head>
<body>
    <h3>Groups of course @ViewBag.CourseName</h3>
    <table>
        <tr>
            <td style="color:blue">@ViewBag.Message</td>
            <td></td>
        </tr>
        @foreach (var group in Model)
        {
    <tr>
        <td>@group.Name</td>
        <td><a href="~/Student/ShowStudents/@group.Id">Select</a></td>
        <td> | </td>
        <td><a href="~/Group/EditGroup/@group.Id">Edit Name</a></td>
        <td> | </td>
        <td><a href="~/Student/AddStudent/@group.Id">Add student</a></td>
        <td> | </td>
        <td><a href="~/Group/DeleteGroup/@group.Id">Delete group</a></td>

    </tr>

        }
    </table>
    <br />
    
</body>
</html>

University/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - University</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Course" asp-action="Index">University</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Main page</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - University 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

University/Views/Student/AddStudent.cshtml
    @using (Html.BeginForm("AddNewStudent", "Student", FormMethod.Post))
    {
        <p>Enter name of new student</p>
        <br />
        <input type="hidden" value="@ViewBag.groupId" name="groupid" />
        <p>First name: </p>
        <input type="text"  name="newfirstname" />
        <br />

        <p>Last name: </p>
        <input type="text"  name="newlastname" />
        <br />
        <br />
        <button name="action" value="save">Add</button>
        <button name="action" value="cancel">Cancel</button>
    }

University/Views/Student/EditStudent.cshtml
@using (Html.BeginForm("ChangeStudentName", "Student", FormMethod.Post))
{
    <p>Enter new name of @ViewBag.FirstName @ViewBag.LastName: </p>
    <br />
    <input type="hidden" value="@ViewBag.StudentId" name="studentid" />
    <p>First name: </p>
    <input type="text" value="@ViewBag.FirstName" name="newfirstname" />
    <br />
    
    <p>Last name: </p>
    <input type="text" value="@ViewBag.LastName" name="newlastname" />
    <br />
    <br />
    <button name="action" value="save">Save</button>
    <button name="action" value="delete">Delete student</button>
    <button name="action" value="cancel">Cancel</button>
}

University/Views/Student/ShowStudents.cshtml
@model IEnumerable<Models.Student>

<!DOCTYPE html>

<html>
<head>
    <title>State University</title>
</head>
<body>
    <h3>Students of group @ViewBag.GroupName</h3>
    <table>
        <tr>
            <td></td>
        </tr>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.FirstName @student.LastName </td>
                <td><a href="~/Student/EditStudent/@student.Id">Edit</a></td>

            </tr>
        }
    </table>
    <br />
    <td><a href="~/Student/AddStudent/@ViewBag.groupId">Add student</a></td>
    <td> | </td>
    <td><a href="~/Group/ShowGroups/@ViewBag.courseId">Back to groups</a></td>

</body>
</html>